personalBlog/apps/blog/urls.py
from django.conf.urls import url

from blog import search_view

from blog.views import BlogIndexView, BlogDetailView, BlogListView, TagSearch

urlpatterns = [
    url(r"^index/$", BlogIndexView.as_view(), name="博客首页"),
    url(r"^detail/$", BlogDetailView.as_view(), name="博客详情"),
    url(r"^list/(?P<blogclassify_id>\d+)/$", BlogListView.as_view(), name="博客分类列表"),
    url(r"^classify/(?P<tag>\d+)$", TagSearch.as_view(), name="标签搜索分类"),
    # url(r"^search/", search_view.MySearch(), name="自定义添加用户信息"),
]

personalBlog/apps/user/urls.py
from django.conf.urls import url

from user.views import UserRegister, UserLoginView, ResetPassWord, PersonalCenter, EditPersoninfo, Board, Revert, \
    QuitLogin

urlpatterns = [
    url(r"^register/$", UserRegister.as_view(), name="用户注册"),
    url(r"^login/$", UserLoginView.as_view(), name="用户登录"),
    url(r"^resetpassword/$", ResetPassWord.as_view(), name="用户重置密码"),
    url(r"^personal/$", PersonalCenter.as_view(), name="用户个人中心"),
    url(r"^edit/$", EditPersoninfo.as_view(), name="用户编辑个人信息"),
    url(r"^board/$", Board.as_view(), name="用户留言"),
    url(r"^revert/$", Revert.as_view(), name="用户留言回复"),
    url(r"^quit/$", QuitLogin.as_view(), name="用户退出登录"),
]

personalBlog/personalBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static

from blog.views import BlogIndexView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 绑定子路由的路由
    url(r'^user/', include("user.urls", namespace='user')),
    url(r'^blog/', include("blog.urls", namespace='blog')),
    url(r'^comments/', include("comments.urls", namespace='comments')),

    # 绑定博客首页的路由
    url(r"^$", BlogIndexView.as_view()),

    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),

]


handler404 = "blog.views.page_not_found"
handler500 = "blog.views.page_error"
handler403 = "blog.views.permission_denied"

personalBlog/apps/comments/models.py
from django.db import models
from db.base_model import BaseModel


# 创建一个用户评论的模型
class CommentsModel(BaseModel):
    content = models.TextField(verbose_name="评论内容")
    parent = models.ForeignKey(to="self", default=0, verbose_name="评论的id")
    user = models.ForeignKey(to="user.UserModel", verbose_name="用户id")
    blogarticle = models.ForeignKey(to="blog.BlogArticle", verbose_name="博客文章id")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "博客评论管理"
        verbose_name_plural = verbose_name

personalBlog/templates/search/search.html
{% extends 'parent/parent.html' %}
{% load static %}
{% load highlight %}

{% block header %}
    <header class="navbar-wrapper">
    <div class="navbar navbar-fixed-top">
        <div class="container cl">
            <a class="navbar-logo hidden-xs" href="{% url 'blog:博客首页' %}">
                <img class="logo" src="{% static 'img/logo01.png' %}" alt="Jason博客"/>
            </a>
            <a class="logo navbar-logo-m visible-xs" href="">Jason博客</a>
            <a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:void(0);"
               onclick="showSide();">&#xe667;</a>
            <nav class="nav navbar-nav nav-collapse w_menu" role="navigation">
                <ul class="cl">
                    <li><a href="{% url 'blog:博客分类列表' 1 %}" data-hover="代码天地">代码天地</a></li>
                    <li><a href="{% url 'blog:博客分类列表' 2 %}" data-hover="机器学习">机器学习</a></li>
                    <li><a href="{% url 'blog:博客分类列表' 4 %}" data-hover="数据分析">数据分析</a></li>
                    <li><a href="{% url 'blog:博客分类列表' 5 %}" data-hover="闲情逸致">闲情逸致</a></li>
                    <li><a href="{% url 'user:用户留言' %}" data-hover="留言足迹">留言足迹</a></li>


                </ul>
            </nav>
             {% comment %}<nav class="navbar-nav navbar-userbar hidden-xs hidden-sm " style="top: 0;">
                <ul class="cl">
                    <li class="userInfo dropDown dropDown_hover">
                        {% if user %}
                        <a href="{% url 'user:用户个人中心' %}" target="_blank">
                            <img class="avatar size-S" src="{{ MEDIA_URL }}{{ user.head }}">
                        </a>&emsp;<a href="#">
                        <input class="btn btn-secondary-outline radius size-S" id="qwer" type="button" value="退出登录"/>
                        </a>
                            {% else %}
                        <a href="{% url 'user:用户登录' %}">
                        <input class="btn btn-secondary-outline radius size-S" type="button" value="登录"/>
                        </a>
                        <a href="{% url 'user:用户注册' %}">
                        <input class="btn btn-secondary-outline radius size-S" type="button" value="注册"/>
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </nav>{% endcomment %}
        </div>
    </div>
</header>
{% endblock %}



{% block content %}
    <section class="container pt-20">
        <div class="col-sm-9 col-md-9">
            <div class="mt-20 bg-fff box-shadow radius mb-5">
                <div class="tab-category">
                    <a href=""><strong class="current">搜索结果</strong></a>
                </div>
            </div>
            <div class="art_content">
                <ul class="index_arc">
                    {% for search in page %}
                        {% if search.object.blog_img %}
                            <li class="index_arc_item">
                                <a href="{% url "blog:博客详情" %}?bid={{ search.object.pk }}" class="pic">
                                    <img class="lazyload" data-original="{{ MEDIA_URL }}{{ search.object.blog_img }}" alt="{{ search.object.blog_title }}">
                                </a>
                                <h4 class="title">
                                    <a href="{% url "blog:博客详情" %}?bid={{ search.object.pk }}">
                                        <b>{% highlight search.object.blog_title with query html_tag "i" css_class "highlight_color" %}</b>
                                    </a>
                                </h4>
                                <div class="date_hits">
                                    <span>Jason</span>
                                    <span>{{ search.object.create_time }}</span>
                                    {% for tag in search.object.blogtag.all %}
                                        <span>
                        <a href="{% url 'blog:标签搜索分类' tag.pk %}">{{ tag.tag_name }}</a>
                    </span>
                                    {% endfor %}
                                    <p class="hits"><i class="Hui-iconfont" title="点击量">&#xe6c1;
                                    </i>{{ search.object.blog_count }}
                                    </p>
                                    <p class="commonts"><i class="Hui-iconfont" title="评论量">&#xe622;
                                    </i>
                                        <span id="sourceId::105" class="cy_cmt_count">{{ search.object.commentsmodel_set.all.count }}
                                        </span>
                                    </p>
                                </div>
                                <div class="desc">
                                    {% highlight search.object.blog_brief with query html_tag "i" css_class "highlight_color" %}
                                </div>
                            </li>
                        {% else %}
                            <li class="index_arc_item no_pic">
                                <h4 class="title">
                                    <a href="{% url "blog:博客详情" %}?bid={{ search.object.pk }}">
                                        <b>{% highlight search.object.blog_title with query html_tag "i" css_class "highlight_color" %}</b>

                                    </a>
                                </h4>
                                <div class="date_hits">
                                    <span>Jason</span>
                                    <span>{{ search.object.create_time }}</span>
                                    {% for tag in search.object.blogtag.all %}
                                        <span>
                        <a href="{% url 'blog:标签搜索分类' tag.pk %}">{{ tag.tag_name }}</a>
                    </span>
                                    {% endfor %}
                                    <p class="hits"><i class="Hui-iconfont" title="点击量">&#xe6c1;
                                    </i>{{ search.object.blog_count }}
                                    </p>
                                    <p class="commonts"><i class="Hui-iconfont" title="评论量">&#xe622;
                                    </i>
                                        <span id="sourceId::105" class="cy_cmt_count">{{ search.object.commentsmodel_set.all.count }}
                                        </span>
                                    </p>
                                </div>
                                <div class="desc">
                                    {% highlight search.object.blog_brief with query html_tag "i" css_class "highlight_color" %}
                                </div>
                            </li>
                        {% endif %}
                    {% empty %}
                        <li style="background-color: #a1e9ee" class="index_arc_item text-l">
                        <br/>
                        <p style="font-size: 20px">未查找到对应的文章哦!</p>
                        <p>请移步其他分类吧!</p>
                    </li>

                    {% endfor %}

                {% if page.paginator.page_range|length >= 2 %}
                     <nav aria-label="Page navigation">
                        {% if page.has_previous %}
                            <a href="{% url 'search:haystack_search' %}?q={{ query }}&page={{ page.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">
                                    <input class="btn btn-success radius size-M" type="button" value="&laquo;">
                                </span>
                            </a>
                        {% endif %}

                        {% for p in page.paginator.page_range %}
                            <a href="{% url 'search:haystack_search' %}?q={{ query }}&page={{ p }}">
                            <input class="btn btn-secondary radius size-M" type="button" value="{{ p }}">
                            </a>
                        {% endfor %}

                        {% if page.has_next %}
                            <a href="{% url 'search:haystack_search' %}?q={{ query }}&page={{ page.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">
                                    <input class="btn btn-success radius size-M" type="button" value="&raquo;">
                                </span>
                            </a>
                        {% endif %}

                    </nav>
                {% endif %}

                </ul>
            </div>
        </div>

        <!--right-->
        <div class="col-sm-3 col-md-3">

            <!--站点搜索-->
            <div class="panel panel-default mb-20">
                <div class="panel-body">
                    <i class="Hui-iconfont" style="float: left;">&#xe62f;&nbsp;</i>
                    <div class="slideTxtBox">
                        <form action="{% url 'search:haystack_search' %}" method="get">
                            <div class="bd">
                               <input type="text" name="q" class="scrollHeight" style="width: 170px;height: 25px" placeholder="请输入您要的搜索的博客关键词"/>
                                <input type="submit" value="搜索" class="btn btn-success radius size-S"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <!--博主信息-->
            <div class="bg-fff box-shadow radius mb-20">
                <div class="tab-category">
                    <a href=""><strong>博主信息</strong></a>
                </div>
                <div class="tab-category-item">
                    <ul class="index_recd">
                        <li class="index_recd_item"><i class="Hui-iconfont">&#xe653;</i>姓名：Jason</li>
                        <li class="index_recd_item"><i class="Hui-iconfont">&#xe70d;</i>职业：Python开发</li>
                        <li class="index_recd_item"><i class="Hui-iconfont">&#xe63b;</i>邮箱：<a href="javascript:;">392391438@qq.com</a>
                        </li>
                        <li class="index_recd_item"><i class="Hui-iconfont">&#xe671;</i>定位：四川 &middot; 成都</li>
                    </ul>
                </div>
            </div>



            <!--分享-->
{% comment %}            <div class="bg-fff box-shadow radius mb-20">
                <div class="tab-category">
                    <a href=""><strong>站点分享</strong></a>
                </div>
                <div class="panel-body">
                    <div class="bdsharebuttonbox Hui-share"><a href="#" class="bds_weixin Hui-iconfont"
                                                               data-cmd="weixin" title="分享到微信">&#xe694;</a><a href="#"
                                                                                                              class="bds_qzone Hui-iconfont"
                                                                                                              data-cmd="qzone"
                                                                                                              title="分享到QQ空间">&#xe6c8;</a>
                        <a href="#" class="bds_sqq Hui-iconfont" data-cmd="sqq" title="分享到QQ好友">&#xe67b;</a> <a href="#"
                                                                                                                class="bds_tsina Hui-iconfont"
                                                                                                                data-cmd="tsina"
                                                                                                                title="分享到新浪微博">&#xe6da;</a>
                        <a href="#" class="bds_tqq Hui-iconfont" data-cmd="tqq" title="分享到腾讯微博">&#xe6d9;</a></div>
                </div>
            </div>{% endcomment %}
        </div>
    </section>

{% endblock %}




{% block footer_js %}

    <script> $(function () {
        $(window).on("scroll", backToTopFun);
        backToTopFun();
    }); </script>
    <script type="text/javascript"
            src="{% static 'plugin/jquery.SuperSlide/2.1.1/jquery.SuperSlide.min.js' %}"></script>
    <script>
        $(function () {
//幻灯片
            jQuery(".slider_main .slider").slide({
                mainCell: ".bd ul",
                titCell: ".hd li",
                trigger: "mouseover",
                effect: "leftLoop",
                autoPlay: true,
                delayTime: 700,
                interTime: 2000,
                pnLoop: true,
                titOnClassName: "active"
            });
//tips
            jQuery(".slideTxtBox").slide({
                titCell: ".hd ul",
                mainCell: ".bd ul",
                autoPage: true,
                effect: "top",
                autoPlay: true
            });
//标签
            $(".tags a").each(function () {
                var x = 9;
                var y = 0;
                var rand = parseInt(Math.random() * (x - y + 1) + y);
                $(this).addClass("tags" + rand)
            });

            $("img.lazyload").lazyload({failurelimit: 3});


        });
    </script>
{% endblock %}