personalBlog/apps/blog/urls.py
from django.conf.urls import url

from blog import search_view

from blog.views import BlogIndexView, BlogDetailView, BlogListView, TagSearch

urlpatterns = [
    url(r"^index/$", BlogIndexView.as_view(), name="博客首页"),
    url(r"^detail/$", BlogDetailView.as_view(), name="博客详情"),
    url(r"^list/(?P<blogclassify_id>\d+)/$", BlogListView.as_view(), name="博客分类列表"),
    url(r"^classify/(?P<tag>\d+)$", TagSearch.as_view(), name="标签搜索分类"),
    # url(r"^search/", search_view.MySearch(), name="自定义添加用户信息"),
]

personalBlog/apps/user/urls.py
from django.conf.urls import url

from user.views import UserRegister, UserLoginView, ResetPassWord, PersonalCenter, EditPersoninfo, Board, Revert, \
    QuitLogin

urlpatterns = [
    url(r"^register/$", UserRegister.as_view(), name="用户注册"),
    url(r"^login/$", UserLoginView.as_view(), name="用户登录"),
    url(r"^resetpassword/$", ResetPassWord.as_view(), name="用户重置密码"),
    url(r"^personal/$", PersonalCenter.as_view(), name="用户个人中心"),
    url(r"^edit/$", EditPersoninfo.as_view(), name="用户编辑个人信息"),
    url(r"^board/$", Board.as_view(), name="用户留言"),
    url(r"^revert/$", Revert.as_view(), name="用户留言回复"),
    url(r"^quit/$", QuitLogin.as_view(), name="用户退出登录"),
]

personalBlog/personalBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static

from blog.views import BlogIndexView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 绑定子路由的路由
    url(r'^user/', include("user.urls", namespace='user')),
    url(r'^blog/', include("blog.urls", namespace='blog')),
    url(r'^comments/', include("comments.urls", namespace='comments')),

    # 绑定博客首页的路由
    url(r"^$", BlogIndexView.as_view()),

    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),

]


handler404 = "blog.views.page_not_found"
handler500 = "blog.views.page_error"
handler403 = "blog.views.permission_denied"

personalBlog/templates/board/board.html
{% extends 'parent/parent.html' %}
{% load static %}

{% block content %}
    <!--导航条-->
    <nav class="breadcrumb">
        <div class="container"><i class="Hui-iconfont">&#xe67f;</i> <a href="/" class="c-primary">首页</a> <span
                class="c-gray en">&gt;</span> <span class="c-gray">留言板</span></div>
    </nav>


<section class="container">
    <div class="col-xs-12 col-md-10 col-md-offset-1 mt-20">


        <div class="bg-fff box-shadow radius mb-20 ">
            <div class="tab-category">
                <a href=""><strong>博主心情</strong></a>
            </div>
            <div class="tab-category-item">

                <div class="tags">
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;
                        <a class="tag" href="">车</a>
                        <a class="tag" href="">马</a>
                        <a class="tag" href="">很</a>
                        <a class="tag" href="">慢</a>
                        &emsp;&emsp;
                        <a class="tag" href="">书</a>
                        <a class="tag" href="">信</a>
                        <a class="tag" href="">很</a>
                        <a class="tag" href="">远</a>
                        &emsp;&emsp;&emsp;
                        <a class="tag" href="">一</a>
                        <a class="tag" href="">生</a>
                        <a class="tag" href="">只</a>
                        <a class="tag" href="">够</a>
                        <a class="tag" href="">爱</a>
                        <a class="tag" href="">一</a>
                        <a class="tag" href="">人</a>
                </div>
            </div>
        </div>


<div class="panel panel-default  mb-20">
<div class="tab-category">
    <a href=""><strong>留言区</strong></a>
</div>
<div class="panel-body">
    <div class="panel-body" style="margin: 0 3%;">
        <div class="mb-20">

<!--用于评论-->
<form action="{% url 'user:用户留言' %}" method="post">
    {% csrf_token %}
    <div class="panel panel-default  mb-20" id="ct">
        <div id="err" class="Huialert Huialert-danger hidden radius">成功状态提示</div>
        <textarea class="board-content" id="textarea1" name="content" style="height:200px;"
                  placeholder="看完不留一发？"> </textarea>
        <input type="hidden" name="parent_id" value="0"/>
        <div class="text-r mt-10">
            <button type="button" class="btn btn-primary radius board"> 发表留言</button>
        </div>
    </div>
</form>
<div class="line"></div>

<ul class="commentList mt-50">
{% for board in boards %}
    {% if board.parent_id == 0 %}
        <li class="item cl"><a href="javascript:;">
            <i class="avatar size-L radius">
                <img alt="" src="{{ MEDIA_URL }}{{ board.user.head }}">
            </i></a>
<div class="comment-main">
    <header class="comment-header">
        <div class="comment-meta">{% if board.user.nickname == "莫言" %}
            <a class="comment-author" href="javascript:;">
                {{ board.user.nickname }}-{{ board.user.phone|get_digit:"11" }}{{ board.user.phone|get_digit:"10" }}{{ board.user.phone|get_digit:"9" }}{{ "****" }}{{ board.user.phone|get_digit:"4" }}{{ board.user.phone|get_digit:"3" }}{{ board.user.phone|get_digit:"2" }}{{ board.user.phone|get_digit:"1" }}
            </a>
    {% else %}
            <a class="comment-author" href="javascript:;">
                {{ board.user.nickname }}</a>
    {% endif %}

        <time title="2014年8月31日 下午3:20" datetime="2014-08-31T03:54:20"class="f-r">
            {{ board.create_time }}
        </time>
            </div>
            </header>
        <div class="comment-body">
            <input type="hidden" class="reply-parent-id" value="{{ comment.pk }}"/>
                {{ board.content|safe }}
<!--展示回复-->
<ul class="commentList">
    {% for reply in  replies %}
        {% if reply.parent_id == board.pk %}
            <li class="item cl"><a href="#"><i
                    class="avatar size-L radius"><img alt="" src="
{{ MEDIA_URL }}{{ reply.user.head }}"></i></a>
                <div class="comment-main">
                    <header class="comment-header">
                        <div class="comment-meta">
                            {% if reply.user.nickname == "莫言" %}
                                <a class="comment-author" href="javascript:;">{{ reply.user.nickname }}{{ reply.user.phone|get_digit:"11" }}{{ reply.user.phone|get_digit:"10" }}{{ reply.user.phone|get_digit:"9" }}{{ "****" }}{{ reply.user.phone|get_digit:"4" }}{{ reply.user.phone|get_digit:"3" }}{{ reply.user.phone|get_digit:"2" }}{{ reply.user.phone|get_digit:"1" }}</a>
                                {% else %}
                                <a class="comment-author" href="javascript:;">{{ reply.user.nickname }}</a>
                            {% endif %}

                            <time title="2014年8月31日 下午3:20"
                                  datetime="2014-08-31T03:54:20"
                                  class="f-r">
                                {{ reply.create_time }}
                            </time>
                        </div>
                    </header>
                    <div class="comment-body">
                        <p>{{ reply.content }}</p>
                    </div>
                </div>
            </li>

        {% endif %}
    {% endfor %}
</ul>
<button class="hf f-r btn btn-default size-S mt-10" name="2">回复</button>
    <input type="hidden" class="reply-parent-id" value="{{ board.pk }}"/>
        </div>
</div>
    </li>
        {% endif %}
            {% endfor %}
</ul>
{% if boards %}
    <div class="mt-20 text-c">
        {% if boards.paginator.page_range|length >= 2 %}
            <nav aria-label="Page navigation">
                {% if boards.has_previous %}
        <a href="{% url 'user:用户留言' %}?page={{ boards.previous_page_number }}"
                                               aria-label="Previous">
    <span aria-hidden="true">
        <input class="btn btn-success radius size-M" type="button" value="&laquo;">
    </span>
        </a>
                {% endif %}

    {% for p in boards.paginator.page_range %}
        <a href="{% url 'user:用户留言' %}?page={{ p }}">
        <input class="btn btn-secondary radius size-M" type="button" value="{{ p }}">
        </a>
    {% endfor %}

    {% if blogarticles.has_next %}
        <a href="{% url 'user:用户留言' %}?page={{ boards.next_page_number }}"                      aria-label="Next">
    <span aria-hidden="true">
         <input class="btn btn-success radius size-M" type="button" value="&raquo;">
    </span></a>
    {% endif %}
    </nav>
            </div>
            {% endif %}
                {% endif %}





<!--用于回复-->
<div class="comment hidden mt-20 ">
    <div id="err2" class="Huialert Huialert-danger hidden radius">成功状态提示</div>
        <textarea class="textarea reply-content" id="textarea2"
                                          style="height:100px;"> </textarea>
        <button type="button" class="btn btn-primary radius mt-10 reply">
            回复
        </button>
        <a class="cancelReply f-r mt-10 ">取消回复</a>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
</section>
{% endblock %}


{% block footer_js %}
    <script type="text/javascript" src="{% static 'plugin/jquery/1.9.1/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugin/layer/3.0/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugin/h-ui/js/H-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugin/pifu/pifu.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script> $(function () {
        $(window).on("scroll", backToTopFun);
        backToTopFun();
    }); </script>
    <script type="text/javascript" src="{% static 'plugin/wangEditor/js/wangEditor.min.js' %}"></script>

    <script type="text/javascript">

        $(function () {
            wangEditor.config.printLog = false;
            var editor1 = new wangEditor('textarea1');
            editor1.config.menus = ['insertcode', 'quote', 'bold', '|', 'emotion', '|', 'undo', 'fullscreen'];
            editor1.create();


            //show reply
            $(".hf").click(function () {
                pId = $(this).attr("name");
                $(this).parents(".commentList").find(".cancelReply").trigger("click");
                $(this).parent(".comment-body").append($(".comment").clone(true));
                $(this).parent(".comment-body").find(".comment").removeClass("hidden");
                $(this).hide();
            });
            //cancel reply
            $(".cancelReply").on('click', function () {
                $(this).parents(".comment-body").find(".hf").show();
                $(this).parents(".comment-body").find(".comment").remove();
            });


            // 实现评论功能
            $(".board").on("click", function () {
                //console.debug(111);
                var self = $(this);
                // 准备发送ajax的数据
                var data = $("form").serialize();
                var board = $(".board-content").val();
                console.debug(board);
                //发动ajax请求
                $.ajax({
                    type: "post",
                    url: "{% url 'user:用户留言' %}",
                    data: data,
                    dataType: "json",
                    success: function (data) {
                        //console.debug(data);
                        if (data.code == 1) {
                            if (confirm("您还没有登录,是否立即登录?")) {
                                location.href = "{% url 'user:用户登录' %}";
                            }
                        } else {
                            alert(data.errmsg);
                            location.href = "{% url 'user:用户留言' %}";
                        }
                    }
                })
            });


            //实现回复功能
            $(".reply").on("click", function () {
                //console.debug(22222)
                var self = $(this);

                // 准备发送ajax的数据
                // 获取回复的内容
                var reply = $(".reply-content").val();
                //console.debug(reply);
                if (reply.length == 0) {
                    alert("回复不能为空哦!")

                } else {
                    //获取留言的id
                    var parent_id = self.parent().prev().val();
                    //console.debug(parent_id);

                    // 准备json数据
                    var data = {
                        "parent_id": parent_id,
                        "reply": reply,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    };

                    //发动ajax请求
                    $.ajax({
                        type: "post",
                        url: "{% url 'user:用户留言回复' %}",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            //console.debug(data);
                            if (data.code == 1) {
                                if (confirm("您还没有登录,是否立即登录?")) {
                                    location.href = "{% url 'user:用户登录' %}";
                                }
                            } else {
                                alert(data.errmsg);
                                location.href = "{% url 'user:用户留言' %}";
                            }
                        }
                    })


                }

            });


            // 退出登录
            $("#qwer").on("click", function () {
                //console.debug(1111)
                var datas = {
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                };
                //发动ajax请求
                $.ajax({
                    type: "post",
                    url: "{% url 'user:用户退出登录' %}",
                    data: datas,
                    dataType: "json",
                    success: function (data) {
                        //console.debug(data);
                        if (data.code == 0) {
                            location.href = "{% url 'blog:博客首页' %}";
                        } else {
                            alert(data.errmsg);
                        }
                    }
                })


            })
        });
    </script>



    <script> $(function () {
        $(window).on("scroll", backToTopFun);
        backToTopFun();
    }); </script>
    <script type="text/javascript"
            src="{% static 'plugin/jquery.SuperSlide/2.1.1/jquery.SuperSlide.min.js' %}"></script>
    <script>
        $(function () {
//幻灯片
            jQuery(".slider_main .slider").slide({
                mainCell: ".bd ul",
                titCell: ".hd li",
                trigger: "mouseover",
                effect: "leftLoop",
                autoPlay: true,
                delayTime: 700,
                interTime: 2000,
                pnLoop: true,
                titOnClassName: "active"
            });
//tips
            jQuery(".slideTxtBox").slide({
                titCell: ".hd ul",
                mainCell: ".bd ul",
                autoPage: true,
                effect: "top",
                autoPlay: true
            });
//标签
            $(".tags a").each(function () {
                var x = 9;
                var y = 0;
                var rand = parseInt(Math.random() * (x - y + 1) + y);
                $(this).addClass("tags" + rand)
            });

            $("img.lazyload").lazyload({failurelimit: 3});

        });
    </script>
{% endblock %}