personalBlog/apps/blog/urls.py
from django.conf.urls import url

from blog import search_view

from blog.views import BlogIndexView, BlogDetailView, BlogListView, TagSearch

urlpatterns = [
    url(r"^index/$", BlogIndexView.as_view(), name="博客首页"),
    url(r"^detail/$", BlogDetailView.as_view(), name="博客详情"),
    url(r"^list/(?P<blogclassify_id>\d+)/$", BlogListView.as_view(), name="博客分类列表"),
    url(r"^classify/(?P<tag>\d+)$", TagSearch.as_view(), name="标签搜索分类"),
    # url(r"^search/", search_view.MySearch(), name="自定义添加用户信息"),
]

personalBlog/apps/comments/urls.py
from django.conf.urls import url

from comments.views import Comments, Reply

urlpatterns = [
    url(r"^comments/$", Comments.as_view(), name="博客评论"),
    url(r"^reply/$", Reply.as_view(), name="博客评论回复"),
]

personalBlog/apps/user/urls.py
from django.conf.urls import url

from user.views import UserRegister, UserLoginView, ResetPassWord, PersonalCenter, EditPersoninfo, Board, Revert, \
    QuitLogin

urlpatterns = [
    url(r"^register/$", UserRegister.as_view(), name="用户注册"),
    url(r"^login/$", UserLoginView.as_view(), name="用户登录"),
    url(r"^resetpassword/$", ResetPassWord.as_view(), name="用户重置密码"),
    url(r"^personal/$", PersonalCenter.as_view(), name="用户个人中心"),
    url(r"^edit/$", EditPersoninfo.as_view(), name="用户编辑个人信息"),
    url(r"^board/$", Board.as_view(), name="用户留言"),
    url(r"^revert/$", Revert.as_view(), name="用户留言回复"),
    url(r"^quit/$", QuitLogin.as_view(), name="用户退出登录"),
]

personalBlog/personalBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static

from blog.views import BlogIndexView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 绑定子路由的路由
    url(r'^user/', include("user.urls", namespace='user')),
    url(r'^blog/', include("blog.urls", namespace='blog')),
    url(r'^comments/', include("comments.urls", namespace='comments')),

    # 绑定博客首页的路由
    url(r"^$", BlogIndexView.as_view()),

    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),

]


handler404 = "blog.views.page_not_found"
handler500 = "blog.views.page_error"
handler403 = "blog.views.permission_denied"

personalBlog/apps/blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from db.base_model import BaseModel


# 创建一个博客文章的分类模型
class BlogClassify(BaseModel):
    # 准备博客文章分类的字段
    class_name = models.CharField(max_length=100, verbose_name="博客文章分类名称")

    def __str__(self):
        return self.class_name

    class Meta:
        verbose_name = "博客文章分类管理"
        verbose_name_plural = verbose_name


# 创建一个博客文章的模型
class BlogArticle(BaseModel):
    # 准备博客文章所需的字段
    blog_title = models.CharField(max_length=200, verbose_name="博客标题")
    blog_brief = RichTextUploadingField(max_length=250, verbose_name="博客摘要")
    blog_content = RichTextUploadingField(verbose_name="博客内容")
    blog_img = models.ImageField(upload_to="blogarticle/%Y%m/%d", null=True, blank=True, verbose_name="博客图片地址")
    blog_status = models.SmallIntegerField(choices=((1, "0积分"),
                                                    (2, "20积分"),
                                                    (3, "30积分"),
                                                    (4, "50积分")), default=1, verbose_name="博客权限")
    blog_is_publish = models.BooleanField(choices=((True, "发表"),
                                                    (False, "未发表")), default=False, verbose_name="博客状态")
    blogclassify = models.ForeignKey(to="BlogClassify", verbose_name="博客分类id")
    blogtag = models.ManyToManyField(to="BlogTag", verbose_name="博客标签")
    blog_count = models.IntegerField(default=0, verbose_name="博客阅读量")

    def __str__(self):
        return self.blog_title

    class Meta:
        verbose_name = "博客文章管理"
        verbose_name_plural = verbose_name


# 创建一个博客的标签模型
class BlogTag(BaseModel):
    # 准备标签所需要的字段
    tag_name = models.CharField(max_length=100, verbose_name="标签名称")

    def __str__(self):
        return self.tag_name

    class Meta:
        verbose_name = "博客标签管理"
        verbose_name_plural = verbose_name


# 创建一个博客首页轮播模型
class Carousel(BaseModel):
    carousel_name = models.CharField(max_length=200, verbose_name="轮播名称")
    img_url = models.ImageField(upload_to="carousel/%Y%m/%d", verbose_name="轮播图片地址")
    order = models.SmallIntegerField(default=0, verbose_name="轮播图片排序")
    show_status = models.BooleanField(choices=((True, "显示"), (False, "不显示")), default=False)
    blogarticle = models.ForeignKey(to="BlogArticle", verbose_name="博客文章")

    def __str__(self):
        return self.carousel_name

    class Meta:
        verbose_name = "轮播管理"
        verbose_name_plural = verbose_name

personalBlog/apps/comments/models.py
from django.db import models
from db.base_model import BaseModel


# 创建一个用户评论的模型
class CommentsModel(BaseModel):
    content = models.TextField(verbose_name="评论内容")
    parent = models.ForeignKey(to="self", default=0, verbose_name="评论的id")
    user = models.ForeignKey(to="user.UserModel", verbose_name="用户id")
    blogarticle = models.ForeignKey(to="blog.BlogArticle", verbose_name="博客文章id")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "博客评论管理"
        verbose_name_plural = verbose_name

personalBlog/apps/blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction

from django.shortcuts import render, redirect

from django.views import View

from blog.models import Carousel, BlogArticle, BlogClassify, BlogTag

from comments.models import CommentsModel

from user.models import UserModel

from django.shortcuts import render

from user.helper import showhead


# 创建个人博客的主页
class BlogIndexView(View):
    # 当用户以GET的方式请求用户首页时
    def get(self, request):
        # 1.查询博客的轮播图片
        carousels = Carousel.objects.filter(show_status=True)

        # 2.查询博客文章的标题和详情
        blogarticles = BlogArticle.objects.filter(is_delete=False, blog_is_publish=True).order_by("-create_time")[:10]
        # 查询用户的头像
        try:
            user_id = request.session.get("id")
            user = UserModel.objects.get(pk=user_id)
        except:
            user = None
        # 3.查询标签
        tags = BlogTag.objects.all()

        # 实现分页功能 Paginator
        paginator = Paginator(blogarticles, 6)
        # 获取当前页面的页码
        page = request.GET.get("page", 1)
        # 获取对应页码的数据
        try:
            blogarticles = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数的时候, 显示第一页
            blogarticles = paginator.page(1)
        except EmptyPage:
            # 页码为空的时候, 显示最后一页
            blogarticles = paginator.page(paginator.num_pages)

        # 查询出所有推荐文章的数据
        data = BlogArticle.objects.filter(is_delete=False, blog_is_publish=True).order_by("-blog_count")[:10]

        # 准备参数
        context = {
            "carousels": carousels,
            "blogarticles": blogarticles,
            "data": data,
            "user": user,
            "tags": tags
        }

        return render(request, "blog/index.html", context=context)


# 博客的详情
class BlogDetailView(View):
    # 用户以GET方式请求
    def get(self, request):
        # 获取博客id
        blog_id = int(request.GET.get("bid"))

        # 根据博客文章的id, 查询出博客的详细信息.及博客的评论与回复
        # 设置一个保存点
        sid = transaction.savepoint()
        try:
            blogarticle = BlogArticle.objects.get(pk=blog_id)
            classify = BlogClassify.objects.get(pk=blogarticle.blogclassify_id)
            # TODO 运行后台报错
            comments = CommentsModel.objects.filter(blogarticle_id=blog_id, parent=0)
            replies = CommentsModel.objects.filter(blogarticle_id=blog_id)
            # comments = CommentsModel.objects.get_queryset().order_by('id')
            # 读者请求一次详情, 博客的阅读量就增加1
            blogarticle.blog_count += 1
        except:
            # 如果出现异常,数据回滚
            transaction.savepoint_rollback()
            return redirect("blog:博客首页")

        # 实现分页功能 Paginator
        paginator = Paginator(list(comments), 8)
        # 获取当前页面的页码
        page = request.GET.get("page", 1)
        # 获取对应页码的数据
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数的时候, 显示第一页
            comments = paginator.page(1)
        except EmptyPage:
            # 页码为空的时候, 显示最后一页
            comments = paginator.page(paginator.num_pages)

        # 准备参数
        context = {
            "blogarticle": blogarticle,
            "classify": classify,
            "comments": comments,
            "user": showhead(request),
            "replies": replies
        }
        # 在没有错误的情况下, 提交数据
        transaction.savepoint_commit(sid)
        blogarticle.save()
        return render(request, "blog/article_detail.html", context=context)


# 创建一个类, 实现对文章的分类展示
class BlogListView(View):
    # 展示对应分类的所有文章
    def get(self, request, blogclassify_id):
        # 根据分类的id, 查询出对应的所有文章
        try:
            classify = BlogClassify.objects.get(pk=blogclassify_id)
            blogarticles = classify.blogarticle_set.filter(is_delete=False).order_by("-create_time")
        except:
            return redirect("blog:博客首页")

        # 实现分页功能 Paginator
        paginator = Paginator(list(blogarticles), 6)
        # 获取当前页面的页码
        page = request.GET.get("page", 1)
        # 获取对应页码的数据
        try:
            blogarticles = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数的时候, 显示第一页
            blogarticles = paginator.page(1)
        except EmptyPage:
            # 页码为空的时候, 显示最后一页
            blogarticles = paginator.page(paginator.num_pages)

        # 准备参数
        context = {
            "blogarticles": blogarticles,
            "classify": classify,
            "user": showhead(request)
        }
        return render(request, 'blog/articles.html', context=context)


# 创建一个类,用于实现标签查找文章
class TagSearch(View):
    # 接受请求参数,查询对应标签的文章
    def get(self, request, tag):
        # 1.接收参数
        tag = int(tag)

        # 2.根据tag查询对应的tag_id
        tag = BlogTag.objects.get(pk=tag)
        # 3.根据标签查找对应的文章
        blogarticles = BlogArticle.objects.filter(is_delete=False, blog_is_publish=True, blogtag=tag).order_by(
            "-create_time")

        # 实现分页功能 Paginator
        paginator = Paginator(blogarticles, 6)
        # 获取当前页面的页码
        page = request.GET.get("page", 1)
        # 获取对应页码的数据
        try:
            blogarticles = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数的时候, 显示第一页
            blogarticles = paginator.page(1)
        except EmptyPage:
            # 页码为空的时候, 显示最后一页
            blogarticles = paginator.page(paginator.num_pages)

        # 4.准备参数
        context = {
            "blogarticles": blogarticles,
            "tag": tag,
            "user": showhead(request)
        }
        return render(request, "blog/tag_search.html", context)


def page_not_found(request):
    return render(request, 'blog/404.html')


def page_error(request):
    return render(request, 'blog/404.html')


def permission_denied(request):
    return render(request, 'blog/404.html')

personalBlog/templates/blog/article_detail.html
{% extends "parent/parent.html" %}
{% load static %}
{% block content %}
    <section class="container">
        <div class="row w_main_row">

            <div class="col-xs-12 col-md-10 col-md-offset-1 mt-20">
            <div class="col-xs-12 col-md-10 col-md-offset-1 mt-20">
               <div class="panel panel-default  mb-10">
        <div class="panel-body pt-10 pb-10">
            <h1 class="c_titile">{{ blogarticle.blog_title }}</h1>
                <input type="hidden" id="reply-bid" value="{{ blogarticle.pk }}"/>
            <p class="box_c">
                <span class="d_time">
                    发布时间：{{ blogarticle.create_time }}</span>
                <span>编辑：<a href="javascript:;">Jason</a>
                </span>
            </p>
            <ul class="infos">
                <li>{{ blogarticle.blog_content|safe }}</li>
                <p align="center" class="pageLink"></p>
            </ul>

            <div class="keybq">
                <p><span>关键字</span>：
                    {% for tag in blogarticle.blogtag.all %}
                        <a href="{% url 'blog:标签搜索分类' tag.pk %}">{{ tag.tag_name }}</a>
                    {% endfor %}
                </p>
            </div>

        </div>
    </div>

                <div class="panel panel-default  mb-20">
                    <div class="tab-category">
                        <a href=""><strong>评论区</strong></a>
                    </div>
                    <div class="panel-body">
                        <div class="panel-body" style="margin: 0 3%;">
                            <div class="mb-20">

<!--用于评论-->
<form action="{% url 'comments:博客评论' %}" method="post" id="te">
    {% csrf_token %}
    <div class="panel panel-default  mb-20" id="ct">
        <div id="err" class="Huialert Huialert-danger hidden radius">成功状态提示</div>
        <textarea class="comment-content" id="textarea1"  name="content" style="height:200px;" placeholder="看完不留一发？"> </textarea>
        <input type="hidden" name="bid" value="{{ blogarticle.pk }}"/>
        <input type="hidden" name="parent_id" value="0"/>
        <div class="text-r mt-10">
            <button type="button" class="btn btn-primary radius fabiao"> 发表评论</button>
        </div>
    </div>

</form>



        <div class="line"></div>
            <ul class="commentList mt-50">
                {% for comment in comments %}
                        {% if comment.parent_id == 0 %}
                            <li class="item cl"><a href="#">
                    <i class="avatar size-L radius"><img alt="" src="{{ MEDIA_URL }}{{ comment.user.head }}"></i></a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                {% if comment.user.nickname == "莫言" %}
                                <a class="comment-author" href="#">{{ comment.user.nickname }}-{{ comment.user.phone|get_digit:"11" }}{{ comment.user.phone|get_digit:"10" }}{{ comment.user.phone|get_digit:"9" }}{{ "****" }}{{ comment.user.phone|get_digit:"4" }}{{ comment.user.phone|get_digit:"3" }}{{ comment.user.phone|get_digit:"2" }}{{ comment.user.phone|get_digit:"1" }}
                                </a>
                                    {% else %}
                                    <a class="comment-author" href="#">{{ comment.user.nickname }}</a>
                                {% endif %}
                                <time title="2014年8月31日 下午3:20" datetime="2014-08-31T03:54:20"
                                      class="f-r">{{ comment.create_time }}
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <input type="hidden" class="reply-parent-id" value="{{ comment.pk }}"/>
                            {{ comment.content|safe }}
                                <!--展示回复-->
<ul class="commentList">
    {% for reply in  replies %}
        {% if reply.parent_id == comment.pk %}
            <li class="item cl"><a href="#"><i class="avatar size-L radius">
<img alt="" src="{{ MEDIA_URL }}{{ reply.user.head }}"></i></a>
    <div class="comment-main">
        <header class="comment-header">
            <div class="comment-meta">
                {% if reply.user.nickname == "莫言" %}
                    <a class="comment-author" href="#">{{ reply.user.nickname }}-{{ reply.user.phone|get_digit:"11" }}{{ reply.user.phone|get_digit:"10" }}{{ reply.user.phone|get_digit:"9" }}{{ "****" }}{{ reply.user.phone|get_digit:"4" }}{{ reply.user.phone|get_digit:"3" }}{{ reply.user.phone|get_digit:"2" }}{{ reply.user.phone|get_digit:"1" }}</a>
                    {% else %}
                    <a class="comment-author" href="javascript:;">{{ reply.user.nickname }}</a>
                {% endif %}

                <time title="2014年8月31日 下午3:20"
                      datetime="2014-08-31T03:54:20" class="f-r">
                    {{ reply.create_time }}
                </time>
    </div>
</header>
            <div class="comment-body">
                <p>{{ reply.content }}</p>
        </div>
    </div>
    </li>
        {% endif %}
                {% endfor %}

            </ul>
                            <button class="hf f-r btn btn-default size-S mt-10" name="2">回复</button>
                            <input type="hidden" class="reply-parent-id" value="{{ comment.pk }}"/>

                        </div>
                    </div>
                </li>
                        {% endif %}
                    {% endfor %}
            </ul>
            <br/>
        <div class="text-c mb-20" id="moreBlog">
        {% if comments.paginator.page_range|length >= 2 %}
                <nav aria-label="Page navigation">
                {% if comments.has_previous %}
                    <a href="{% url 'blog:博客详情' %}?bid={{ blogarticle.pk }}&page={{ comments.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">
                     <input class="btn btn-success radius size-M" type="button" value="&laquo;">
                    </span>
                        </a>
                    {% endif %}

                    {% for p in comments.paginator.page_range %}
                        <a href="{% url 'blog:博客详情' %}?bid={{ blogarticle.pk }}&page={{ p }}">
                    <input class="btn btn-secondary radius size-M" type="button" value="{{ p }}">
                    </a>
                    {% endfor %}

                    {% if blogarticles.has_next %}
                            <a href="{% url 'blog:博客详情' %}?bid={{ blogarticle.pk }}&page={{ comments.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">
                            <input class="btn btn-success radius size-M" type="button" value="&raquo;">
                                </span>
                                </a>
                            {% endif %}

                        </nav>
        {% endif %}

        </div>

         <!--用于回复-->
        <div class="comment hidden mt-20 ">
            <div id="err2" class="Huialert Huialert-danger hidden radius">成功状态提示</div>

            <textarea class="textarea reply-content" id="textarea2" style="height:100px;"> </textarea>
            <button type="button" class="btn btn-primary radius mt-10 reply">回复</button>
            <a class="cancelReply f-r mt-10 ">取消回复</a>
        </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            </div>

        </div>


    </section>
{% endblock %}





{% block footer_js %}
    <script type="text/javascript" src="{% static 'plugin/jquery/1.9.1/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugin/layer/3.0/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugin/h-ui/js/H-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugin/pifu/pifu.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script> $(function () {
        $(window).on("scroll", backToTopFun);
        backToTopFun();
    }); </script>
    <script type="text/javascript" src="{% static 'plugin/wangEditor/js/wangEditor.min.js' %}"></script>

    <script type="text/javascript">

        $(function () {
            wangEditor.config.printLog = false;
            var editor1 = new wangEditor('textarea1');
            editor1.config.menus = ['insertcode', 'quote', 'bold', '|', 'emotion', '|', 'undo', 'fullscreen'];
            editor1.create();


            //show reply
            $(".hf").click(function () {
                pId = $(this).attr("name");
                $(this).parents(".commentList").find(".cancelReply").trigger("click");
                $(this).parent(".comment-body").append($(".comment").clone(true));
                $(this).parent(".comment-body").find(".comment").removeClass("hidden");
                $(this).hide();
            });
            //cancel reply
            $(".cancelReply").on('click', function () {
                $(this).parents(".comment-body").find(".hf").show();
                $(this).parents(".comment-body").find(".comment").remove();
            });


            // 实现评论功能
            $(".fabiao").on("click", function () {
                //console.debug(111);
                var self = $(this);
                // 准备发送ajax的数据
                var data = $("form").serialize();
                //获取博客文章的id
                var bid = parseInt(self.siblings('input').val());
                //console.debug(bid);
                // 获取评论内容
                var comment = $(".comment-content");
                console.debug(comment);


                //发动ajax请求
                $.ajax({
                    type: "post",
                    url: "{% url 'comments:博客评论' %}",
                    data: data,
                    dataType: "json",
                    success: function (data) {
                        //console.debug(data);
                        if (data.code == 1) {
                            if (confirm("您还没有登录,是否立即登录?")) {
                                location.href = "{% url 'user:用户登录' %}";
                            }
                        } else {
                            alert(data.errmsg);
                            location.href = "{% url 'blog:博客详情' %}?bid=" + data.data;
                        }
                    }
                })


            });


            //实现回复功能
            $(".reply").on("click", function () {
                //console.debug(22222)
                var self = $(this);

                // 准备发送ajax的数据
                // 获取回复的内容
                var reply = $(".reply-content").val();
                //console.debug(reply);
                if (reply.length == 0) {
                    alert("回复不能为空哦!")

                } else {
                    //获取博客文章的id
                    var bid = $("#reply-bid").val();
                    //console.debug(bid);
                    //获取评论的id
                    var parent_id = self.parent().prev().val();
                    //console.debug(parent_id);

                    // 准备json数据
                    var data = {
                        "bid": bid,
                        "parent_id": parent_id,
                        "reply": reply,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    };

                    //发动ajax请求
                    $.ajax({
                        type: "post",
                        url: "{% url 'comments:博客评论回复' %}",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            //console.debug(data);
                            if (data.code == 1) {
                                if (confirm("您还没有登录,是否立即登录?")) {
                                    location.href = "{% url 'user:用户登录' %}";
                                }
                            } else {
                                alert(data.errmsg);
                                location.href = "{% url 'blog:博客详情' %}?bid=" + data.data;
                            }
                        }
                    })


                }

            });
                // 退出登录
                $("#qwer").on("click", function () {
                //console.debug(1111)
                    var datas = {
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    };
                    //发动ajax请求
                    $.ajax({
                        type: "post",
                        url: "{% url 'user:用户退出登录' %}",
                        data: datas,
                        dataType: "json",
                        success: function (data) {
                            //console.debug(data);
                            if (data.code == 0) {
                                location.href = "{% url 'blog:博客首页' %}";
                            } else {
                                alert(data.errmsg);
                            }
                        }
                    })
            })


        });
        </script>

{% endblock %}