personalBlog/apps/user/urls.py
from django.conf.urls import url

from user.views import UserRegister, UserLoginView, ResetPassWord, PersonalCenter, EditPersoninfo, Board, Revert, \
    QuitLogin

urlpatterns = [
    url(r"^register/$", UserRegister.as_view(), name="用户注册"),
    url(r"^login/$", UserLoginView.as_view(), name="用户登录"),
    url(r"^resetpassword/$", ResetPassWord.as_view(), name="用户重置密码"),
    url(r"^personal/$", PersonalCenter.as_view(), name="用户个人中心"),
    url(r"^edit/$", EditPersoninfo.as_view(), name="用户编辑个人信息"),
    url(r"^board/$", Board.as_view(), name="用户留言"),
    url(r"^revert/$", Revert.as_view(), name="用户留言回复"),
    url(r"^quit/$", QuitLogin.as_view(), name="用户退出登录"),
]

personalBlog/personalBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static

from blog.views import BlogIndexView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 绑定子路由的路由
    url(r'^user/', include("user.urls", namespace='user')),
    url(r'^blog/', include("blog.urls", namespace='blog')),
    url(r'^comments/', include("comments.urls", namespace='comments')),

    # 绑定博客首页的路由
    url(r"^$", BlogIndexView.as_view()),

    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),

]


handler404 = "blog.views.page_not_found"
handler500 = "blog.views.page_error"
handler403 = "blog.views.permission_denied"

personalBlog/apps/user/models.py
from django.core.validators import RegexValidator
from django.db import models

from db.base_model import BaseModel


# 创建一个用户的模型类
class UserModel(BaseModel):
    # 准备用户表所需要的字段
    phone = models.CharField(max_length=11,
                             validators=[
                                 RegexValidator(r"^1[3-9]\d{9}", "手机号码格式不正确!")
                             ],
                             verbose_name="用户手机号码")
    password = models.CharField(max_length=64, verbose_name="用户密码")
    nickname = models.CharField(max_length=100, default="莫言", verbose_name="用户昵称")
    sex = models.SmallIntegerField(choices=((1, "男"), (2, "女"), (3, "保密")), default=3, verbose_name="用户性别")
    user_status = models.SmallIntegerField(choices=((1, "正常"),
                                                    (2, "禁止评论"),
                                                    (3, "禁止登陆")),
                                           default=1, verbose_name="用户状态")

    user_integral = models.DecimalField(max_digits=9, decimal_places=2, default=1000, verbose_name="用户积分")

    user_buyblogarticle = models.ManyToManyField(to="blog.BlogArticle", verbose_name="用户购买博客文章")

    # intro = models.CharField(max_length=255, default="留下点你的个性再走呗!", verbose_name="用户个人简介")
    # # 添加一个用户头像的字段
    head = models.ImageField(upload_to="head/%Y%m/%d", default="head/avatar.jpg", verbose_name="用户头像")

    def __str__(self):
        return self.nickname

    class Meta:
        db_table = "user"
        verbose_name = "用户管理"
        verbose_name_plural = verbose_name


# 创建一个用户留言的类
class BoardModel(BaseModel):
    content = models.TextField(verbose_name="留言内容")
    parent = models.ForeignKey(to="self", default=0, verbose_name="留言id")
    user = models.ForeignKey(to="user.UserModel", verbose_name="留言用户id")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "用户留言管理"
        verbose_name_plural = verbose_name

personalBlog/apps/user/forms.py
from django import forms

from user.helper import set_password
from user.models import UserModel


# 创建一个验证粉丝用户注册的Form类
class UserRegisterForm(forms.Form):
    # >>>>>>1.验证手机号码字段
    phone = forms.CharField(error_messages={
        "required": "手机号码必须填写!"
    })
    # >>>>>>2.验证用户输入的密码
    password = forms.CharField(min_length=8,
                               max_length=16,
                               error_messages={
                                   "required": "密码必须要填写!",
                                   "min_length": "密码至少8个字符!",
                                   "max_length": "密码最多16个字符!"
                               })
    # >>>>>>3.验证用户第二次输入的密码
    password2 = forms.CharField(error_messages={
        "required": "密码必须填写!"
    })

    # >>>>>>4.定义一个方法,验证手机号码是否已经被注册
    def clean_phone(self):
        # 获取用户提交的手机号码
        phone = self.cleaned_data.get("phone")
        # 到数据库进行查看,看该手机号码是否已经被注册
        flag = UserModel.objects.filter(phone=phone).exists()
        # 对返回的结果进行判断
        if flag:
            # 在查询结果为True的情况下,抛出异常,提示用户该手机号码已经被注册,请前往登录界面,或者更换手机号码
            raise forms.ValidationError('该手机号码已经被注册!请前往登录界面登录!或者更换手机号码注册!')
        else:
            # 在查询结果为False的情况下
            return phone

    # >>>>>>5.定义一个方法,验证用户两次输入的密码是否一致
    def clean(self):
        # 首先获取用户两次输入的密码
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        # 在两次密码都为真的情况下, 判断两次的密码是否一致
        if password and password2 and password != password2:
            # 在两次密码不为空且不相等的情况下 执行
            raise forms.ValidationError({"password2": "两次输入的密码不一致!"})
        else:
            # 在密码相等和密码不为空的情况下 执行
            return self.cleaned_data


# 创建一个验证粉丝用户登录的Form类
class UserLoginModelForm(forms.ModelForm):
    class Meta:
        # 关联模型类
        model = UserModel
        # 选择所需要的
        fields = ['phone', 'password']
        # 自定义错误信息
        error_messages = {
            "phone": {
                "required": "手机号码必填!"
            },
            "password": {
                "required": "密码必填!"
            }
        }

    # 综合校验, 判读用户输入的手机号码和密码是否正确
    def clean(self):
        # >>>>>1.先后去用户传过来的电话号码
        phone = self.cleaned_data.get('phone')
        # >>>>>2.先到数据库中查看是否有该手机号码
        try:
            user = UserModel.objects.get(phone=phone)
        except UserModel.DoesNotExist:
            raise forms.ValidationError({"phone": "该手机号码未注册,请输入已经注册手机号码!或者前往注册页面注册!"})
        # >>>>>3.在手机号码合法的情况下, 验证密码的合法性
        password = self.cleaned_data.get('password')
        # 将用户传过来的密码进行加密处理,才能和数据库中的数据进行判断
        password = set_password(password)
        if user.password != password:
            # 在密码不正确的情况下
            raise forms.ValidationError("密码错误!")
        else:
            # 在密码正确的情况下
            # 1.<<< 先将查询到的用户信息保存到session之中
            self.cleaned_data["user"] = user
            # 2.<<< 再将清洗后的数据返回
            return self.cleaned_data


# 创建一个验证用户重置密码的Form类
class ResetPassWordForm(forms.Form):
    # 首先验证手机号码是否填写
    phone = forms.CharField(error_messages={
        "required": "手机号码必须填写!"
    })
    # 验证用户输入的密码
    password = forms.CharField(min_length=8,
                               max_length=16,
                               error_messages={
                                   "required": "密码必须填写!",
                                   "min_length": "密码最少8个字符!",
                                   "max_length": "密码最长为16个字符!"
                               })
    password2 = forms.CharField(error_messages={
        "required": "密码必须填写!"
    })

    # 定义一个方法, 验证用户侧手机号码是否已经注册
    def clean_phone(self):
        # 获取用户传来的手机号码
        phone = self.cleaned_data.get("phone")
        # 到数据库查询此手机号码是否已经存在
        flag = UserModel.objects.filter(phone=phone).exists()
        # 对查询结果进行判断
        if flag == 0:
            # 没有查询到对应的手机号码
            raise forms.ValidationError("该手机号码还未注册!请前往注册页面进行注册!")
        else:
            # 查询到了手机号码
            return phone

    # 定义一个方法, 验证两次输入的密码是否一致
    def clean(self):
        # 首先获取两次输入的密码
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        # 判断两次的密码是否都为真, 且两次的密码一致
        if password and password2 and password != password2:
            # 在两次密码为真且不相等的情况下执行
            raise forms.ValidationError({"password2": "两次输入的密码不一致!"})
        else:
            # 两次密码为真,且相等的情况下执行
            return self.cleaned_data

personalBlog/apps/user/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from django.views import View

from comments.forms import CommentsForm
from comments.helper import json_msg
from db.base_view import VerifyLogin
from user.forms import UserRegisterForm, UserLoginModelForm, ResetPassWordForm
from user.helper import set_password, login, showhead, check_login
from user.models import UserModel, BoardModel


# 创建一个视图类,实现用户的注册功能
class UserRegister(View):
    # 用户以GET方式请求用户注册界面
    def get(self, request):
        return render(request, 'user/register.html')

    # 当用户以POST方式提交数据的时候执行此函数
    def post(self, request):
        # 1.接受参数
        data = request.POST
        # 2.验证参数的合法性
        # >>>>1.创建一个form表单验证的对象,来进行数据合法性的验证
        form = UserRegisterForm(data)
        if form.is_valid():
            # 在数据合法的情况下执行
            # 接受清洗后的数据
            # 1.<<<< 接收手机号码
            phone = form.cleaned_data.get("phone")
            # 2.<<<< 接收密码
            password = form.cleaned_data.get("password")
            # 3.将密码加密
            password = set_password(password)
            # 将接受的数据,保存到数据当中
            UserModel.objects.create(phone=phone, password=password)
            # 保存到数据库成功
            return redirect("user:用户登录")
        else:
            # 在数据不合法的情况下
            return render(request, 'user/register.html', {"form": form})


# 创建一个视图类, 实现用户的登录
class UserLoginView(View):
    # 当用户以GET方式请求,请求该页面时
    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        # 接受用户提交的数据
        data = request.POST
        # 判断数据的合法性
        # 创建一个form验证对象
        form = UserLoginModelForm(data)
        # 判断数据的合法性
        if form.is_valid():
            # 在数据合法的情况下
            # 1.<<< 将回传数据的用户信息, 保存在session中
            user = form.cleaned_data.get("user")
            # 2.<<< 将用户信息保存到数据session中
            login(request, user)
            # 判断用户发起要求登录的网址是否存在
            referer = request.session.get("referer")
            # 判断referer是否存在
            if referer:
                return redirect(referer)
            else:
                return redirect('blog:博客首页')
        else:
            # 在数据合法的情况下
            return render(request, 'user/login.html', {"form": form})


# 定义一个类,完成用户重置密码的功能(前提要检查用户是否已经登录)
class ResetPassWord(View):
    # 展示重置密码界面
    def get(self, request):
        return render(request, 'user/resetpassword.html')

    def post(self, request):
        # 1.接受参数
        data = request.POST
        # 2.验证参数的合法性
        # >>>>1.创建一个form表单验证的对象,来进行数据合法性的验证
        form = ResetPassWordForm(data)
        if form.is_valid():
            # 在数据合法的情况下执行
            # 接受清洗后的数据
            # 1.<<<< 接收手机号码
            phone = form.cleaned_data.get("phone")
            # 2.<<<< 接收密码
            password = form.cleaned_data.get("password")
            # 3.将密码加密
            password = set_password(password)
            # 将接受的数据,保存到数据当中
            UserModel.objects.filter(phone=phone).update(password=password)
            # 保存到数据库成功
            return redirect("user:用户登录")
        else:
            # 在数据不合法的情况下
            return render(request, 'user/resetpassword.html', {"form": form})


# 定义一个类用户展示用户的个人中心
class PersonalCenter(VerifyLogin):
    def get(self, request):
        user_id = request.session.get("id")
        # 查询用户信息
        data = UserModel.objects.get(pk=user_id)
        # 准备参数
        context = {
            "data": data
        }
        return render(request, "user/personal.html", context=context)


# 定义一个类, 实现编辑个人信息
class EditPersoninfo(VerifyLogin):
    def get(self, request):
        user_id = request.session.get("id")
        # 查询用户信息
        data = UserModel.objects.get(pk=user_id)
        # 准备参数
        context = {
            "data": data
        }
        return render(request, "user/edit_personal.html", context=context)

    def post(self, request):
        # 接受参数
        data = request.POST
        # 接收头像参数
        head = request.FILES.get("head")
        # 获取用户的id
        user_id = request.session.get("id")
        user = UserModel.objects.get(pk=user_id)
        # 判断头像的数据合法性
        if head is not None:
            # 保存用户头像
            user.head = head
        user.save()
        user.sex = data.get("sex")
        user.nickname = data.get("nickname")
        user.phone = data.get("phone")
        user.save()
        return redirect("user:用户个人中心")


# 创建一个用户留言板
class Board(View):
    # 展示留言板
    def get(self, request):
        # 查询所有的留言
        boards = BoardModel.objects.filter(is_delete=False, parent=0)
        replies = BoardModel.objects.filter(is_delete=False)

        # 实现分页功能 Paginator
        paginator = Paginator(list(boards),8)
        # 获取当前页面的页码
        page = request.GET.get("page", 1)
        # 获取对应页码的数据
        try:
            boards = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数的时候, 显示第一页
            boards = paginator.page(1)
        except EmptyPage:
            # 页码为空的时候, 显示最后一页
            boards = paginator.page(paginator.num_pages)
        # 将留言传到前台
        context = {
            "boards": boards,
            "user": showhead(request),
            "replies": replies
        }
        return render(request, "board/board.html", context=context)

    def post(self, request):
        # 接受用户传来的数据
        data = request.POST
        data = dict(data)
        # 获取当前用户的id
        user_id = request.session.get("id")
        if user_id is None:
            return JsonResponse(json_msg(1, "您还未登录!"))
        # 判断用户的权限是否足够
        if UserModel.objects.get(pk=user_id).user_status != 1:
            return JsonResponse(json_msg(2, "您已经被禁言!7天后解除限制!"))
        # 获取留言的id
        parent_id = int(data.get("parent_id")[0])

        # 判断留言的合法性
        content = data.get("content")
        content = "".join(content)

        # 判断留言长度是否足够
        data["content"] = content
        # 创建form验证对象
        form = CommentsForm(data)
        # 判断
        if form.is_valid():
            # 数据合法  将数据保存到数据库
            BoardModel.objects.create(
                content=content,
                user_id=user_id,
                parent_id=parent_id
            )
            return JsonResponse(json_msg(0, "留言成功!"))
        else:
            # 数据不合法
            return JsonResponse(json_msg(3, "评论不能为空!"))


# 创建一个类实现留言回复
class Revert(VerifyLogin):
    # 展示留言板
    def get(self, request):
        # 查询所有的留言
        boards = BoardModel.objects.filter(is_delete=False, parent=0)
        replies = BoardModel.objects.filter(is_delete=False)

        # 实现分页功能 Paginator
        paginator = Paginator(list(boards), 8)
        # 获取当前页面的页码
        page = request.GET.get("page", 1)
        # 获取对应页码的数据
        try:
            boards = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数的时候, 显示第一页
            boards = paginator.page(1)
        except EmptyPage:
            # 页码为空的时候, 显示最后一页
            boards = paginator.page(paginator.num_pages)

        # 将留言传到前台
        context = {
            "boards": boards,
            "user": showhead(request),
            "replies": replies
        }
        return render(request, "board/board.html", context=context)

    def post(self, request):
        # 接受参数
        data = request.POST
        data = dict(data)
        # 获取当前用户的id
        user_id = request.session.get('id')
        # 判断该用户是否具备评价资格
        if UserModel.objects.get(pk=user_id).user_status != 1:
            return JsonResponse(json_msg(2, "您已经被禁言!7天后解除限制!"))

        # 判断评论id是否存在
        parent_id = int(data.get("parent_id")[0])
        try:
            BoardModel.objects.get(pk=parent_id)
        except BoardModel.DoesNotExist:
            return JsonResponse(json_msg(3, "回复的留言不存在!"))

        # 主要是对评论内容进行判断合法性
        content = data.get("reply")
        content = ''.join(content)
        # 判断评论的长度够不够
        # 创建form对象, 验证评论内容的合法性
        data["content"] = content
        form = CommentsForm(data)
        # 判断数据的合法性
        if form.is_valid():
            # 数据合法的情况下
            # 将数据保存到数据库中
            BoardModel.objects.create(
                content=content,
                parent_id=parent_id,
                user_id=user_id,
            )
            return JsonResponse(json_msg(0, "回复成功!"))
        else:
            return JsonResponse(json_msg(4, "回复不能为空!"))

        # TODO  用户个人中心 搜索页的头像问题, 退出登录


# 创建一个类, 实现对用户个人登录信息的删除
class QuitLogin(VerifyLogin):
    def post(self, request):
        # 清除session中的登录信息
        request.session.flush()
        return JsonResponse(json_msg(0, "清除登录成功!"))

personalBlog/templates/user/edit_personal.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>

    <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
        修改个人信息
    </title>
    <link rel="stylesheet" href="{% static 'personal/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'personcenter/dist/css/bootstrap.css' %}" type="text/css"/>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <script src="{% static 'personal/js/jquery.js' %}"></script>
    <script src="{% static 'personcenter/dist/js/jquery.js' %}"></script>
    <script src="{% static 'personal/js/custom.js' %}"></script>
    <script src="{% static 'personcenter/dist/js/bootstrap.js' %}"></script>
    <style>
        .head {
            margin: 0px auto;
            background: no-repeat center;
            border-radius: 50%;
            border: 0px solid #fff;
            box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0), 0px 4px 8px 0px rgba(0, 0, 0, 0);
            width: 95px;
            height: 95px;
            position: relative;
        }

        .infor-pic {
            margin-left: 10px;
            float: left;
            width: 6rem;
            height: 6rem;
            border-radius: 50%;
        }

        .infor-pic img {
            width: 100%;
            height: 100%;
        }

        .input-file {
            position: absolute;
            right: 0;
            top: 0;
            cursor: pointer;
            z-index: 1;
            font-size: 30em;
            *font-size: 30px;
            opacity: 0;
            filter: alpha(opacity=0)
        }

    </style>
</head>
<body>
<div class="accordion-wrap">
    <div class="accordion">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <a href="javascript:void(0)"><i class="fa fa-user"></i>&nbsp;个人简介</a>

            <div class="nav profile">

                <div class="head">
                    <div class="infor-pic">
                         <img src="{{ MEDIA_URL }}{{ data.head }}" />
                            <input type="file" name="head"  class=""/>
                    </div>
                </div>
                <br/>
                <input class="form-control" style="width: 150px" name="nickname" value="{{ data.nickname|default_if_none:"莫言" }}"/>


            </div>

            <a href="javascript:void(0)"><i class="fa fa-envelope"></i>&nbsp;详细信息</a>

            <div class="nav">
                <div class="chat">

                </div>
                <a href="javascript:void(0)">
                    &nbsp;电话号码&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span><input class="form-control" id="exampleInputPassword3" name="phone" value="{{ data.phone }}"/></span>
                </a>
                <a href="javascript:void(0)">
                    &nbsp;性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="infor-tele">
                        <label class="am-radio-inline">

                            {% if data.sex == 1 %}
                                <input type="radio" name="sex" value="1" checked="checked" data-am-ucheck>男
                            {% else %}
                                <input type="radio" name="sex" value="1" data-am-ucheck>男
                            {% endif %}
                        </label>
                        <label class="am-radio-inline">
                            {% if data.sex == 2 %}
                                <input type="radio" name="sex" value="2" checked="checked" data-am-ucheck>女
                            {% else %}
                                <input type="radio" name="sex" value="2" data-am-ucheck>女
                            {% endif %}
                        </label>
                        <label class="am-radio-inline">
                            {% if data.sex == 3 %}
                                <input type="radio" name="sex" value="3" checked="checked" data-am-ucheck>保密
                            {% else %}
                                <input type="radio" name="sex" value="3" data-am-ucheck>保密
                            {% endif %}
                        </label>
                    </i>
                </a>
            </div>

{% comment %}            <i style="font-size: 20px"></i><input type="submit" value="确认修改" class="btn btn-link glyphicon glyphicon-floppy-disk"/>{% endcomment %}

        <button type="submit" class="btn btn-link">
  &nbsp;<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>&nbsp;确认修改
</button>
        </form>
    </div>

</div>
</body>
</html>

personalBlog/templates/user/login.html
{% extends 'parent/father.html' %}
{% load static %}
{% block title %}
    用户登录
{% endblock %}

{% block content %}
    <div id="particles-js">
    <div class="login">
        <div class="login-top">
            登录
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="login-center clearfix">
                <div class="login-center-img"><img src="{% static 'register_login/img/name.png' %}"/></div>
                <div class="login-center-input">
                    <input type="text" name="phone" value="{{ request.POST.phone }}" placeholder="请输入您的电话号码"/>
                    <div class="login-center-input-text">电话号码</div>
                    <span style="color:#ff2c28">{{ form.errors.phone.0 }}</span>

                </div>
            </div>
            <div class="login-center clearfix">
                <div class="login-center-img"><img src="{% static 'register_login/img/password.png' %}"/></div>
                <div class="login-center-input">
                    <input type="password" name="password" value="" placeholder="请输入您的密码"/>
                    <div class="login-center-input-text">密码</div>
                    <span style="color:#ff2c28">{{ form.errors.password.0 }}</span>
                </div>
            </div>

            <div class="login-button">
                <input type="submit" value="登   录" style="background-color: #5e9eed; width: 246px; height: 36px"/>
            </div>

            <br/>

                <a style="color: #0c59e9" href="{% url 'user:用户注册' %}" >&emsp;&emsp;&emsp;&emsp;&nbsp;去 注 册</a>

            <a style="color: #0c59e9" href="{% url 'user:用户重置密码' %}" >&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;忘记密码</a>

                    </form>
        <div class="sk-rotating-plane"></div>



    </div>
    </div>

{% endblock %}

personalBlog/templates/user/personal.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>
    <title>
        个人中心
    </title>
    <link rel="stylesheet" href="{% static 'personal/style.css' %}" type="text/css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="{% static 'personal/js/jquery.js' %}"></script>
    <script src="{% static 'personal/js/custom.js' %}"></script>
    <style>
        .head {
    margin: 0px auto;
    background: no-repeat center;
    border-radius: 50%;
    border: 0px solid #fff;
    box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0), 0px 4px 8px 0px rgba(0, 0, 0, 0);
    width: 95px;
    height: 95px;
    position: relative;
}
        .infor-pic {
    margin-left: 2px;
    float: left;
    width: 6rem;
    height: 6rem;
    border-radius: 50%;
}

.infor-pic img {
    width: 100%;
    height: 100%;
}
    </style>
</head>
<body>
<div class="accordion-wrap">
    <div class="accordion">
        <a href="javascript:void(0)"><i class="fa fa-user"></i>&nbsp;个人简介</a>
        <div class="nav profile">
            <div class="head">
                <div class="infor-pic">
                    <img src="{{ MEDIA_URL }}{{ data.head }}" />
                </div>
            </div>
            <h3>{{ data.nickname|default_if_none:"莫言" }}</h3>


        </div>
        <a href="javascript:void(0)"><i class="fa fa-envelope"></i>&nbsp;详细信息</a>

        <div class="nav">
            <div class="chat">

            </div>
            <a href="javascript:void(0)">
                &nbsp;电话号码&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>{{ data.phone }}</span>
            </a>
            <a href="javascript:void(0)">
                &nbsp;性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                	    			<i  class="infor-tele">
                        <label class="am-radio-inline">
                    {% if data.sex == 1 %}
                    <input type="radio" disabled="disabled" checked="checked"  value="{{ data.sex }}" data-am-ucheck>男
                    {% else %}
                        <input type="radio" disabled="disabled" value="{{ data.sex }}" data-am-ucheck>男
                    {% endif %}
				        </label>
                    <label class="am-radio-inline">
                        {% if data.sex == 2 %}
                        <input type="radio" disabled="disabled" checked="checked"  value="{{ data.sex }}" data-am-ucheck>女
                    {% else %}
                        <input type="radio" disabled="disabled"  value="{{ data.sex }}" data-am-ucheck>女
                    {% endif %}
				        </label>
                    <label class="am-radio-inline">
                        {% if data.sex == 3 %}
                        <input type="radio" disabled="disabled" checked="checked"  value="{{ data.sex }}" data-am-ucheck>保密
                    {% else %}
                        <input type="radio" disabled="disabled" value="{{ data.sex }}" data-am-ucheck>保密
                    {% endif %}
				        </label>
	    			</i>
            </a>
        </div>
 <a href="{% url 'user:用户编辑个人信息' %}"><i style="font-size: 20px">&raquo;&nbsp;</i>编辑个人信息</a>
    </div>

    </div>
</body>
</html>